### ISSUE TITLE
fail2ban does not auto start on debian jessie

### ISSUE THREAD

**Issue by richbreton** [fusionpbx/fusionpbx#1029]
1. OS: Debian Jessie
2. Fusion Version: 3.8 and Master
3. Issue: After install and reboot fail2ban and firewall  rules are no longer there on startup. I'm guessing this has something to do with systemd but I have not looked into it any further at this point

**Comment by andyfor** [comment]
Hey Rich. I noticed on latest Fusion version 3.9 install that Fail2Ban didn't start. Increased log level info for fail2ban and it was because jail.local referenced freeswitch-dos filter but freeswitch-dos.conf did not exist in filter.d directory. It did in older versions of Fusion.
Anyway might not be same issue for you but for me I created freeswitch-dos filter in filter.d directory (based on older version I had) and Fail2Ban kicked into life. Basically it wouldn't start because it complained about missing filter.

Cheers
Andy

**Comment by richbreton** [comment]
@andyfor thanks a lot I'll look into that!

**Comment by richbreton** [comment]
@andyfor yea it looks like during install some code evals that the fail2ban filters already exist so it doesnt attempt to write them and just tries starting as seen here:

Processing triggers for systemd (215-17+deb8u1) ...

Checking log-auth-failures
     [ENABLED] log-auth-failures - Was False!
fail2ban filter for freeswitch already done!
/bin/grep: /etc/fail2ban/jail.local: No such file or directory

**Comment by richbreton** [comment]
great ill fix this tomorrow - good catch

**Comment by andyfor** [comment]
sweet.

**Comment by richbreton** [comment]
Looks Good even after Reboot. Closing Ticket
-------------------------------------------------------------
Jul 24 05:21:24 vultr.guest fail2ban[463]: Starting authentication failure monitor: fail2ban.
root@vultr:~# service fail2ban status
● fail2ban.service - LSB: Start/stop fail2ban
   Loaded: loaded (/etc/init.d/fail2ban)
   Active: active (running) since Fri 2015-07-24 05:21:24 UTC; 3min 45s ago
  Process: 463 ExecStart=/etc/init.d/fail2ban start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/fail2ban.service
           └─545 /usr/bin/python /usr/bin/fail2ban-server -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid

Jul 24 05:21:24 vultr.guest fail2ban[463]: Starting authentication failure monitor: fail2ban.
root@vultr:~# uptime
 05:25:17 up 4 min,  1 user,  load average: 0.00, 0.00, 0.00
