### ISSUE TITLE
conflict between page_extension (*8) and extension_queue (*800)

### ISSUE THREAD

**Issue by lcx** [fusionpbx/fusionpbx#1039]
The default setup hast page_extension configured as `*8[ext]` `^\*8(\d{2,7})$` and the extension_queue as `*800[ext]` `^\*800(.*)$`
if you have a 2 digit extension and dial `*80012` it would actually be used as page_extension for extension 0012.

**Comment by davidwjacob** [comment]
If you upgrade to the latest version properly your page should now be *724 and not *8 anymore. see the wiki about upgrading:

Delete the following dialplans from each domain then run Advanced -> Upgrade -> App Defaults. If using XML handler for the dialplan flush memcache. If using dialplans XML on the file system resave one of the dialplans to have FusionPBX rewrite the XML files.
user_exists - call_timeout variable was added
extension-intercom - It has been renamed to 'page-extension'
eavesdrop - Change *88[ext] to *33[ext] so that it doesn't conflict with page-extension at *8[ext]
user_status - Has been renamed to 'agent_status'
page - Dialplan has been simplified.
valet_park_out - Changed regex variable from $1 to $2
local_extension - failure handler was added to support call forward on busy and no answer

**Comment by markjcrane** [comment]
Appears to be answered closing the issue.
