### ISSUE TITLE
Call Detail Records not download or play

### ISSUE THREAD

**Issue by rbaan0618** [fusionpbx/fusionpbx#1078]
Good afternoon,

When you use the Call Detail Records and click over the play looks like is play but nothing is play, if you click over download you receive a file call recordings.php with 0 bytes, appreciate if can give some guide to catch this bugs. the version is 3.8 and is running in Ubuntu 12.04.

Thanks and regards,

Roberto Baan

**Comment by rbaan0618** [comment]
I am using Apache and database postgres,

**Comment by rbaan0618** [comment]
Any one have this issue?? appreciate any info. 

Thanks in advanced.

**Comment by moteus** [comment]
Windows/WAMP 2.2/FusionPBX git master/Chrome
Download/Play records from CDR works correct.

**Comment by rbaan0618** [comment]
Thanks for your reply but in our case we test with all the browser and when we hit the download in the Call Detail Records a php file is download with 0 bytes no the recording, all the other functions of download are working fine like voicemail etc.. but in the case of the CDR report this is what happen have you any idea can create this????

**Comment by moteus** [comment]
Your filename is `//archive/2015/Aug/07/5b87b8ac-3d2a-11e5-8974-f365650467f7.mp3`
May be problem in first double slash. (On my system there also exists but it works)
They appear because [1](https://github.com/fusionpbx/fusionpbx/blob/master/app/xml_cdr/xml_cdr.php#L371-L376) and [2](https://github.com/fusionpbx/fusionpbx/blob/master/app/xml_cdr/xml_cdr.php#L399)

Also you can try set `recordings` option in default settings or in domain settings.

**Comment by rbaan0618** [comment]
Thanks to your response i going to check that part in the CDR report, to say the files are in the right place we download manually, to refresh we are in ubuntu 12.05 FusionPBX 3.8. let me know if anything else come to your mind that create this situation, the strange is when you click in the download what is download is a recordings.php file with 0 bytes and looks like try download the recordings.php program.

Thanks one more time...

**Comment by moteus** [comment]
I found similar problem with voicemail. instead download I just redirect to voicemail_edit.php.
I add `ob_end_clean();` before `fpassthru($fd);` [here](https://github.com/fusionpbx/fusionpbx/blob/master/app/voicemails/resources/classes/voicemail.php#L357). I found this solution on `php.net`

In `recordings.php` (xml_cdr use it) before `fpassthru` there [ob_clean()](https://github.com/fusionpbx/fusionpbx/blob/master/app/recordings/recordings.php#L101).
This is not works for me in voicemail unless I add `exit;` in the end of function `message_download`.

I really not php programmer and not shure how it works because of that I can not create PR.

**Comment by markjcrane** [comment]
This has been rewritten please try it on the latest version of FusionPBX 4.1 or higher.
