### ISSUE TITLE
Cannot create conference room without pins

### ISSUE THREAD

**Issue by b1den** [fusionpbx/fusionpbx#1153]
conf center ping length 0 & no pins on "room" page.
nginx gateway timeout.
tried pg,sqlite,apache,nginx.

**Comment by markjcrane** [comment]
It was not designed for a pin length of 0. Pin length is required by design as it identifies the room. With no pin number if it were possible there could only be one conference room per conference center. Right now you want no pin length sponsor the feature or use the other conference feature which doesn't require a pin number. You can find it in menu manager and add a group to it. So that it is visible and an alternative to conference center.
