### ISSUE TITLE
Device line password change out of the blue

### ISSUE THREAD

**Issue by steve14** [fusionpbx/fusionpbx#1241]
Investigating Device line password change. A gxv device suddenly de-registers. Line password does not match extension password. Login into device line, the password is different from the one provided on extension level. How is that possible? How can i investigate this issue?
Thanks in advance

**Comment by markjcrane** [comment]
If the password is changed from device_edit it does not change the extension password. If you change it from accounts -> extensions when its assigned to a device it will change the password. The provisioning is built to work with the local system or work as a standalone system which is why it saves the password in one direction.
