### ISSUE TITLE
when leaving a voicemail press 1 option doesn't work

### ISSUE THREAD

**Issue by lodperera** [fusionpbx/fusionpbx#1378]
Fusion 4.1
FS 1.6.5

1. Called in to an extension and left until it timesout and end up in the voicemail.
2. recorded a message and pressed a digit.
3. When voice prompt says press 1 to listen, it gives an error .

line 511 http://pastebin.com/Y9z8i8qG

Regards
Oshada

**Comment by markjcrane** [comment]
Looks like you have a problem with mod_shout.

**Comment by markjcrane** [comment]
2016-01-07 10:20:44.533452 [ERR] mod_shout.c:84 Error allocating mpg123 handle! Invalid decoder choice. (code 9)
2016-01-07 10:20:44.533452 [ERR] mod_shout.c:901 Error: MPG123 Error at mod_shout.c:686.
2016-01-07 10:20:44.533452 [ERR] mod_shout.c:904 Error from mpg123: Invalid mpg123 handle. (code 10)

Please follow up with this on #freeswitch IRC channel this looks like an issue with your system rather than a FusionPBX bug.

**Comment by lodperera** [comment]
Figured out the solution.

Advanced--> settings --> mod shout decoder --> leave blank

I have actually selected one of the options which gave this issue. 

Thank you for your time. Hope this helps another guy. :)

**Comment by markjcrane** [comment]
Mine is set to shout decoder: amd64
Thanks for reporting back what helped.
