### ISSUE TITLE
Fax Server - Newbie

### ISSUE THREAD

**Issue by eviltnl** [fusionpbx/fusionpbx#1448]
Hi everyone,
I have a fax server. I want to check its functionality. What should I do. (Inbound and Outbound).
Thank you very much :)

**Comment by bdstephenson** [comment]
Try sending a fax to: 8884732963

This is HP test fax service, when it successfully receives a fax, it will send a test fax back the caller ID number provided (so make sure the number you set routes back to fax server).

You can also use faxtoy.net for just testing outbound, there you can see how the fax turned out on the remote side.

**Comment by eviltnl** [comment]
thank you very much.

I can't send fax to mail with fusion. i created gateways and outbound.
Can you hlep me ?

**Comment by markjcrane** [comment]
Setup up the SMTP settings in Advanced -> Default settings. Check the /tmp directory after sending a test to see if it worked or to find out what went wrong.

**Comment by felixrafael** [comment]
Was this issued resolved. I can receive faxes to my configured email but I cannot send faxes. They get all stuck in the fax queue.
Any ideas why?
I'm using Fusionpbx 4.2.1 on Debian.
