### ISSUE TITLE
no voicemail notifcations for E.164 Extenions-Fusion pbx

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#1812]
2016-08-12 09:53:14.588069 [DEBUG] freeswitch_lua.cpp:365 DBH handle 0x7f43a8065020 Connected.
2016-08-12 09:53:14.588069 [DEBUG] freeswitch_lua.cpp:382 DBH handle 0x7f43a8065020 released.
**2016-08-12 09:53:14.588069 [NOTICE] switch_cpp.cpp:1360 [mwi_subscribe] voicemail +18324089902@192.168.1.10 has 0/0 message(s)**

After changing the Extension to 10 digit, it lit up the mwi..

**2016-08-12 09:55:37.968055 [NOTICE] switch_cpp.cpp:1360 [mwi_subscribe] voicemail 8324089902@192.168.1.10 has 1/0 message(s)**

**Comment by moteus** [comment]
I think problem with `+` sign. Voicemail id should be digit only so user can dial it via keypad.

**Comment by kkoilada** [comment]
you are right that voicemail id should be digit only, however, it has nothing to do with extensions isn't it? I registered my extension as E.164 format, so if I do it this way then voicemail notifications won't work??

**Comment by mafoo** [comment]
extensions are expected to only contain digits otherwise we run into a lot of dial plan issues trying to support multilingual letters (let alone matching characters that get interpreted as regex expressions)
I would suggest you change the extension to loose the leading + or you will likely run into other problems as well, don't forget you can create dialplan entries to convert number formats or alternatively use mod_translate to deal with other number formats

**Comment by markjcrane** [comment]
Agreed with mafoo. If you remove the + it will work fine.

**Comment by kkoilada** [comment]
thank you very much guys.. Appreciated..
