### ISSUE TITLE
fs_path scenario sends sip invite with private IP to the phone

### ISSUE THREAD

**Issue by kkoilada** [fusionpbx/fusionpbx#2042]
Hi,

When phones registered and home in to the same server, the server sends invite to the phone with the public IP, however, when the phone registered to a different server but belongs to same domain, the server which proxies the call sends the sip invite with private IP, which doesn't get out the server gateway as it has no idea how to route to that network. I checked NDLB and nat settings but no luck. Any tweaks that will allow it to work ? your help is much appreciated.

Thank you

**Comment by DigiDaz** [comment]
Try rport on the phone if it available

**Comment by markjcrane** [comment]
fs_path is designed to proxy the call to the server it registered to.

**Comment by kkoilada** [comment]
Mark,
I believe that you have overlooked the issue by simply closing the ticket. The issue is sending sip invite with private IP which doesn't land on the IP phone as the private IP is not routable in BGP domain. FYI, I am trying to deploy SBC hiding the Fusionpbx which would take care of this private IP routing issue but the real issue will remain intact with no resolution.

Thanks

@DigiDaz 
I already have enabled rport on the phone and it doesn't fix the issue.

**Comment by markjcrane** [comment]
I think github issues are designed to report bugs and from now on that is how I will treat it. Free support requests are given as time permits and should not be considered an expectation or entitlement. Your customers will pay you or your company for the work you are expecting us to help you with.

We may add an official forum in the future but since the project is rated on the github issues and many of them are really just support requests. Your issue is related to freeswitch and fs_path not specifically fus

**Comment by DigiDaz** [comment]
kkoilada Head on over to http://www.fusionpbxforums.com we will see if we can help you out there.

**Comment by kkoilada** [comment]
Thank you very much my friend for providing directions. I look forward meeting you in those forums.

Thank you 
Krish

**Comment by kkoilada** [comment]
Digi,

Hi Digi,how are you? I've seen your chat exchange on the issue json_Store
db for webrtc... I am facing the same issue as well. I am wondering if you
can help me resolving this issue.

Thanks
krish
