### ISSUE TITLE
New custom Menus don't work

### ISSUE THREAD

**Issue by dedayoa** [fusionpbx/fusionpbx#2228]
Hello,
I have gone through the following steps to get custom menu to work in a new domain, but all to no avail.

1. I created (under group manager) a group, and assigned the same permissions as user.
2. I created a new menu, and picked a few samples from the default menu, assigning them to the group I created above.
3. I then went ahead to create a new user, assigning it to the group I created
4. After logging in with the new user, there is no menu

I have done the same, using a superadmin I created on the new domain, and although the superadmin gets the "superadmin" menu, the new user does not get any menu.

How does one go about creating a new menu?

N.B: I'm on the master branch, version 4.3.0, commit: 4a6b29449b3e909ce4f8224cbd729e09b73d90cb

**Comment by markjcrane** [comment]
You likely missed something otherwise the default menu wouldn't work either. For example did you assign that group to parent menus? In other words did you assign the user to the main menus. If you assigned them to sub menus well then you wouldn't see them because you wouldn't have permissions to the parent.

Need help beyond go to the website and click on support.
