### ISSUE TITLE
Unable to play or download voicemail messages

### ISSUE THREAD

**Issue by bigfishvoice** [fusionpbx/fusionpbx#2258]
Version: 4.2.1
FS: 1.4.26

We are unable to play or download load voice mail messages from the App > Voicemail > Message.  The play option shows the red timeline but never moves.  Clicking on the download link takes us to a blank page.  Messages are being saved in PGSQL.  Haven't had any issues before, this is a recent thing.  Maybe related to issue #2255.

**Comment by andyfor** [comment]
Just fyi, seems to work ok for me on 4.2.1, 1.6.12.
Does it work if you are logged in as superadmin? Just curious if some sort of permissions issue.
Andy

**Comment by bigfishvoice** [comment]
I've tried it as a user and a superadmin.  Are your messages being saved in the dB?

**Comment by andyfor** [comment]
Ahh good point, they are being stored in the file system not the DB.

**Comment by bigfishvoice** [comment]
Additionally, found that I'm unable to delete any messages from Apps > Voicmail > Messages

**Comment by markjcrane** [comment]
This has been fixed. To increase security I added is_uuid check to the code for the play, download, and delete. It failed because is_uuid was checking for uuid version 4 and the uuid that was generated was from freeswitch 1.4 was uuid version 1 or 2. I made the is_uuid function more generic so it would work with uuid version 1,2,3 and 4.
