### ISSUE TITLE
music on hold not changing

### ISSUE THREAD

**Issue by andycol** [fusionpbx/fusionpbx#2323]
if you change the hold music on an extension, it shows that it has changed but still plays the old music

**Comment by bayden10** [comment]
I'm having the same issue but I see errors in the log - Error allocating mpg123 handle! Invalid decoder choice.

**Comment by bayden10** [comment]
I have resolved the error of invalid decoder by changing Advanced --> Settings --> Mod Shout Decoder to blank.  Extension music selected still will not change. Still plays default.

**Comment by bayden10** [comment]
Monitoring fs_cli I find see this warning when placing an internal call on hold trying to use the Local/New music on hold directory, same happens when external calls are placed:

`2017-03-02 13:36:59.563824 [WARNING] switch_core_media.c:3906 RFC2543 from March 1999 called; They want their 0.0.0.0 hold method back.....
2017-03-02 13:36:59.563824 [DEBUG] switch_channel.c:1844 (sofia/internal/123456@10.10.10.10:5068) Callstate Change ACTIVE -> HELD
2017-03-02 13:36:59.703867 [DEBUG] switch_ivr.c:623 sofia/internal/123456@pbx.domain.com Command Execute playback(local_stream://pbx.domain.com/New)
EXECUTE sofia/internal/123456@pbx.domain.com playback(local_stream://pbx.domain.com/New)
2017-03-02 13:36:59.703867 [WARNING] mod_local_stream.c:806 Unknown source pbx.domain.com/New, trying 'default'`

Global/Default on hold music then plays.

**Comment by markjcrane** [comment]
It means there is no 'New' category so it used default music on hold category instead.
