### ISSUE TITLE
Please consider tagging 4.0.1 and 4.2.2

### ISSUE THREAD

**Issue by daniel-lucio** [fusionpbx/fusionpbx#2332]
Since the release of 4.0 there have been several security fixes, the same since 4.2.1. I think it is a good idea tagging new micro-releases

**Comment by markjcrane** [comment]
No one should be using 4.0 anymore. If you are leaving your customers on 4.0 then you are misrepresenting fusionpbx and doing a disservice to your customers.  It's not safe to use 4.0 hundreds of bugs and security fixes since then have been fixed in the 4.2 branch. I'm not joking put in the work and upgrade. 4.0 is not being maintained it is end of life so it will not be getting tagged.  Version 4.2.1 will be marked as 4.2.2 soon. We don't have the resources to maintain several versions back if someone really wants that money is needed on a continual for that maintainenance work. Catching 4.0 security fixes would require at least a week full time and bug fixes that are fixed in 4.2.x would take another couple weeks. All of those changes would take testing and risk destabilizing 4.0. Alternative put in work and test 4.2 practice upgrading or pay for help to do the upgrade for you.

**Comment by daniel-lucio** [comment]
Your argument has been the same all time, not saying it is not true or false.

when 3.6 was out, you said 3.4 was full of bugs
when 3.8 was out, you said 3.6 was full of bugs
when 4.0 was out, you said 3.8 was full of bugs
now 4.2 is out, and you say 4.0 is full of bugs

so, 4.2 will be full of bugs when 4.4 is out?

I have been working on 4.2 for a while, but when a customer of mine finds a bug, I always backport the patch to 4.0 if it applies.
