### ISSUE TITLE
Cannot Register Endpoints using UDP but Works TCP

### ISSUE THREAD

**Issue by ernestkm** [fusionpbx/fusionpbx#2666]
Hi

When trying to register endpoints, Yealink, Cisco etc. using the UDP transport type is is not working but it works with TCP transport type.

Any Idea what could be causing this?

Thanks and Regards
Ernest Manamela

**Comment by mafoo** [comment]
There could be all manor of things, the problem with udp is packets are allowed to be discarded by the network without retransmissions which causes problems with some protocols.
You might be better off coming on the IRC to discuss the issues you are having

**Comment by daniel-lucio** [comment]
Just a guess, your UDP packets could be longer than 512 bytes.

**Comment by ruslanguns** [comment]
@ernestkm  I bet you this is an ISP issue, you may confirm it by setting up a VPN in your office. Try first to reproduce your issue with a Softphone like Jitsy or xLite then if you still have it, try with a Free VPN in order to not waste money "Windscribe" then if it works you may confirm by yourself confirm if you go to premium VPN or talk to your ISP to unblock your ports. 
Hope you understand my poor English.

**Comment by markjcrane** [comment]
Yealink doesn't rotate the SIP port automatically when using UDP like it does for TCP. So when using UDP you have to set the port number.
http://forum.yealink.com/forum/archive/index.php?thread-881.html
account.1.sip_listen_port = 5060

**Comment by ernestkm** [comment]
Hi All

Thanks for the feedback and the Help, Mark is correct once I have changed the Local SIP Port the phones work.

**Comment by markjcrane** [comment]
It also may depend on the type of NAT that is performed on the firewall.

**Comment by ernestkm** [comment]
Thanks Mark I have also realized after your advise that SIP ALG was active on the Router which could have also cause the problem.
