### ISSUE TITLE
Admin Password Lockout redux

### ISSUE THREAD

**Issue by sboothe** [fusionpbx/fusionpbx#2688]
I have been very oddly locked out of a fresh install that I've invested considerable time into. I did not change or lose the password but upon logout to test a new user I can no longer log back in as admin? (error: invalid user/password)

I have even followed the previously recommended process for creating a temporary user and reseting the password and that doesn't even work.

Any advice would be greatly appreciated. Thanks.

**Comment by ruslanguns** [comment]
If you still have root access to your server you can use the following guide 

http://wiki.fusionpbx.com/index.php?title=Password_Recovery

**Comment by sboothe** [comment]
Followed those instructions now and still the same issue.
Note: The output from the last command stated: "UPDATE 0".
It kind of worries me that this may happen again if I start over.

**Comment by mafoo** [comment]
sboothe UPDATE 0 suggests it didn't find the username for updating in the guide replace 'superadmin' with the username you normally login with and see if that helps.
Or what is the result of 'select username from v_users;' in postgresql

**Comment by mafoo** [comment]
alternatively you can use the reset_admin_password script I submitted into a PR if it is accepted
https://github.com/fusionpbx/fusionpbx-install.sh/pull/102

**Comment by markjcrane** [comment]
I think there is a good chance that your problem was not the password at all. You need to consider that FusionPBX framework is multi-tenant. This means that when you login the domain matters. So if you are logging in with your browser from a different IP address or domain name in the URL from what it was installed to then it will deny access. Lets say you installed it inside your network with an internal IP address and then you moved the server to the data center. Your server could have a new address but the domain name in Advanced -> Domains is still the old IP address. This can also happen if you use port forwarding and you are accessing it from the outside. Again if the Domain does not match then you need to login with the domain that is there. It normally picks up the domain from the browser URL. You can also get it from the username if you login with username@domain as the user name.

Also the link given to the wiki that was given for password recover is the hard way to do it. Then the second way that was given is a brand new way that mafoo just created. There is another way to do it suggested in youtube.com/fusionpbx.
