### ISSUE TITLE
Asterisk as a Switch

### ISSUE THREAD

**Issue by ernestkm** [fusionpbx/fusionpbx#2725]
Hi

On the new version can we still use asterisk as and not freeswitch?
I know on the old version we could, Also If that works what features am I going to lose?

This is a Question and not a Bug.

**Comment by markjcrane** [comment]
This is a better question for a phone call or irc.

**Comment by markjcrane** [comment]
Also seems like the wrong place to ask why would we want to convince you to use Asterisk when FusionPBX is clearly based on FreeSWITCH and therefore you know which one we prefer.

**Comment by markjcrane** [comment]
I really don't want to disrespect the work placed in Asterisk it was many peoples first taste of open source telephony and deserves some respect for that.

Your question isn't clear if you ask can FusionPBX work with Asterisk as the back end engine instead of FreeSWITCH that would require a large amount of work.

If you are asking can FusionPBX with FreeSWITCH connect to Asterisk and work with it the answer is yes. But without a clearer questions these are just guesses for what you meant.
