### ISSUE TITLE
App Extension Summary shows nothing

### ISSUE THREAD

**Issue by neradpeter** [fusionpbx/fusionpbx#2830]
No data in Extension Summary page... add user role, admin role to user.. user has extensions..user is calling and receiving calls from this extensions

**Comment by neradpeter** [comment]
only works if using postreslq 👎

**Comment by markjcrane** [comment]
PostgreSQL is the officially supported database for FusionPBX. Why because its creator chose to support PostgreSQL as the primary supported database. Its a good idea for us to pick one and focus on it. Most things however still work MySQL and SQLite. And this tool will likely be updated to fix that. But if you want the best experience use PostgreSQL.

**Comment by neradpeter** [comment]
Ok thanks
