### ISSUE TITLE
ring group strategy rollover 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#686]
```
The problem is when the first ringing extension picked up, the other didn't 
ringing if second call coming in.

The problem is solved when I removed domain_name from line 421 of 
app/ring_groups/index.lua:

 extension_status = "show channels like "..destination_number.."@"..domain_name;

changed to 

 extension_status = "show channels like "..destination_number.."@";

Please check if this is the issue.
```

Original issue reported on code.google.com by `spw...@gmail.com` on 15 Aug 2014 at 7:12

**Comment by badcrc** [comment]
I noticed this as well, I was having problems in this scenario:

- sequence ring group with the extension 100 and 101 on it
- the 101 tells me that somethings when the 100 is idle, the calls go directly to 101

I looked at the lua for the ring groups and checked how the matching is done. Turns out that doing the "show channels llike destination_number" also matches a lot of things (for example someone calling a number with an 100 on it) even with the aditional check for looking for the domain.

I'm currently trying this fix: exploding the show channels reply and looking for the "destionation_number@domain_name", seems to be working for now, I will send the fix after more testing!
