### ISSUE TITLE
I can not create users

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fusionpbx/fusionpbx#958]
```
When you are creating users, groups do not appear, this does not create new 
users

FusionPBX 3.8.3, new installation and Sqlite

```

Original issue reported on code.google.com by `cabi...@gmail.com` on 14 May 2015 at 6:22

**Comment by xil3so** [comment]
Same here, there's no way to create new user since FusionPBX requires to provide group and it's not possible to provide group.

Debian Jessie, 3.16.0-4-amd64, Apache2, sqlite;
I've tried "Advanced -> Upgrade -> Schema" but no success.
I have to say that I can see/add/remove groups in "Advanced -> Group Manager".

UGLY HACK (in contemporary Firefox, but have to work in Chrome, too) - the point is
- open "Accounts -> User Manager"
- click plus sign to open "Add user" form
- *right* click on this disabled "Group" pull-down menu
-- select "Inspect element" or similar
    (additional window should open underneath with HTML source of the page AND code responsible for the form selected)
-- click that small triangle left from "<select class"
-- you'll see "<option value=""></option>" underneath -- that's the problem
-- click once on this row and press F2 on your keyboard (or right click on it then: "Edit as HTML") on it
-- just enter: <option value="public">public</option>
   (please note: incorrect, because "value" is supposed to be id of the group. Either way, it let's you get past this)
-- click once outside this editor window -- *poof*, "public" next to bold "Group" option should became available.
- fill all the other mandatory options and click "Create account"
- you should see your account created but WITHOUT group assigned (because that one provided in the user creation form was invalid) - just edit the account and add any group you need (just in case it would really make a difference) -- now, just out of the curiosity, you may inspect proper drop-down box and see the proper values.

Disclaimer: yes, that's ugly as hell, I know. I just wanted to create an account, that is.

**Comment by markjcrane** [comment]
3.8.3 is old. 3.9 is the dev branch. When you are on the latest version then I will pay attention to your bug that I can't duplicated on my 4.0.

**Comment by markjcrane** [comment]
Maybe you are having problems because you haven't followed the upgrade instructions at:
http://wiki.fusionpbx.com/index.php?title=Upgrade

**Comment by xil3so** [comment]
Thanks for sharing that, it indeed resolved that issue - the problem was that numerous sources (including https://github.com/fusionpbx/fusionpbx-scripts/blob/master/install/centos6/install_fusionpbx.sh ) point out either to old stable version or the dev version (my installation was fresh one, as, I believe, the person from original comment)

Nb. please consider *not* forcing installation of fusionpbx as the default site - I decided to run it on a separate port on apache and I believe it's better approach (especially because it's easier to limit access to the service - something in par with your attempt to limit brute force attempts to the service with iptables and fail2ban); ultimately I'll probably go for nginx exclusively for fusionpbx and postgresql (as recommended).

Thanks, Mark.

**Comment by markjcrane** [comment]
CentOS doesn't have an updated install script.

"consider not forcing installation of fusionpbx as the default site"
Its not forced you can run fusionpbx as the main website in the root directory or you can run it in the website directory in a directory named fusionpbx. If you decide to run it from inside the fusionpbx folder in the website directory then you cannot rename that directory as the code needs to be aware of where it is. Its hard coded to look for the fusionpbx directory.
